### ISSUE TITLE
Where is located repository or branch of https://sabbath-school.adventech.io/ru/

### ISSUE THREAD

**Issue by KeyJoo** [Adventech/sabbath-school-web#1]
# Where is located repository or branch of sabbath-school.adventech.io

- [ ] I want to see repository of [sabbath-school.adventech.io](https://sabbath-school.adventech.io/ru/)

**Comment by VitalikL** [comment]
@KeyJoo It would be the same as regular Sabbath School lessons. `github.com/Adventech/sabbath-school-lessons` we use hugo in `web` directory to compile the web version.
